import Head from 'next/head'
import BlogCard from '@/components/BlogCard'

async function getPosts() {
  const response = await fetch('https://dummyjson.com/posts?limit=10')
  return response.json()
}

export default async function Home() {
  const { posts } = await getPosts()

  return (
    <div className='flex flex-col gap-y-4'>
      <Head>
        <title>Next.js 13 | Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/letter-m.png" />
      </Head>
      {posts.map(post => (
        <BlogCard key={post.id} {...post} />
      ))}

    </div>
  )
}
